-- TODO: 
    -- Test if works
    -- Get number of rows deleted (https://stackoverflow.com/a/16721588)

USE TSQL_ASSIGNMENT;
GO

IF OBJECT_ID('DELETE_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_CUSTOMERS;
GO 

CREATE PROCEDURE DELETE_ALL_CUSTOMERS AS 

BEGIN
    DELETE FROM CUSTOMER
    WHERE CUSTID > 0 AND CUSTID < 500;
    
END;

GO

EXEC DELETE_ALL_CUSTOMERS;

SELECT * FROM CUSTOMER;