USE TSQL_ASSIGNMENT;
GO

IF OBJECT_ID('DELETE_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_PRODUCTS;
GO 

CREATE PROCEDURE DELETE_ALL_PRODUCTS AS 
BEGIN
    BEGIN TRY
        DELETE FROM PRODUCT WHERE PRODID >= 1000 AND PRODID <= 2500;
        SELECT @@ROWCOUNT;
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END; 
    END CATCH
END;
GO

EXEC DELETE_ALL_PRODUCTS;

SELECT * FROM PRODUCT;