
USE TSQL_ASSIGNMENT;
GO

IF OBJECT_ID('UPD_CUST_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_CUST_SALESYTD;
GO 

CREATE PROCEDURE UPD_CUST_SALESYTD @PCUSTID INT AS 
BEGIN
    BEGIN TRY
        UPDATE CUSTOMER SET SALES_YTD *= @PRODPRICE WHERE CUSTIS = @PCUSTID
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END; 
    END CATCH
END;
GO

EXEC INSERT_NAME;

SELECT * FROM TABLE_NAME;