USE TSQL_ASSIGNMENT;
GO

IF OBJECT_ID('GET_CUSTOMER_STRING') IS NOT NULL
DROP PROCEDURE GET_CUSTOMER_STRING;
GO 

CREATE PROCEDURE GET_CUSTOMER_STRING @PCUSTID INT, @PRETURNSTRING NVARCHAR(1000) OUTPUT AS 
BEGIN
    BEGIN TRY

        DECLARE @OCUSTNAME NVARCHAR(100);
        SELECT @OCUSTNAME = CUSTNAME FROM CUSTOMER WHERE CUSTID = @PCUSTID;

        DECLARE @OSTATUS NVARCHAR(7);
        SELECT @OSTATUS = STATUS FROM CUSTOMER WHERE CUSTID = @PCUSTID;

        DECLARE @OSALES_YTD MONEY;
        SELECT @OSALES_YTD = SALES_YTD FROM CUSTOMER WHERE CUSTID = @PCUSTID;

        SET @PRETURNSTRING = CONCAT('Customer ID: ', @PCUSTID, ' Name: ', @OCUSTNAME, ' Status: ', @OSTATUS, ' Sales YTD: ', @OSALES_YTD);
        
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END; 
    END CATCH;
END;
GO

DECLARE @PRETURNSTRING NVARCHAR(1000);
EXEC GET_CUSTOMER_STRING @PCUSTID = 1, @PRETURNSTRING = OUTPUT
BEGIN 
    PRINT @PRETURNSTRING;
END;
GO