-- TODO:
    -- Test
    -- add requirements from spec sheet

USE TSQL_ASSIGNMENT;
GO

IF OBJECT_ID('ADD_PRODUCT') IS NOT NULL
DROP PROCEDURE ADD_PRODUCT;
GO

CREATE PROCEDURE ADD_PRODUCT @PPRODID INT, @PPRODNAME NVARCHAR(100), @PSELLING_PRICE MONEY AS

BEGIN
    INSERT INTO PRODUCT(PRODID, PRODNAME, SELLING_PRICE, PRICE_YTD)
    VALUES(@PPRODID, @PPRODNAME, @PSELLING_PRICE, 0)
END;

GO

SELECT * FROM PRODUCT;

